# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Arash Pourhabibi
title: A computer geek, a food lover, and a traveler-wannabe
email: arash.pourhabibi@epfl.ch
website: arash.pourhabibi.info

# Social links
twitter_username: ArashPourhabibi
github_username:  neo-apz
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: neo_apz
linkedin_username: arashpourhabibizarandi
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is [Arash](https://en.wikipedia.org/wiki/Arash) (Persian: آرش) (aka NEO).
  I am a PhD candidate at the [School of Computer and Communication Sciences](http://ic.epfl.ch/),
  [EPFL](https://www.epfl.ch/en/home/), and a doctoral research assistant at [PARSA](http://parsa.epfl.ch)
  under supervision of [Prof. Babak Falsafi](http://parsa.epfl.ch/~falsafi/).
  I did my master’s in Software Engineering at the Department of CSE and IT of
  [Shiraz University](http://en.wikipedia.org/wiki/Shiraz_University),
  where I also received my B.Sc. in Software Engineering.

# Interests Section
# interests_title: Research Interests
interests_content: | # this will include new lines to allow paragraphs
  I am broadly interested in the field of systems and interdisciplinary systems problems
  found in modern, large-scale datacenters.
  My current research revolves around efficiency and sustainability enhancement of server systems
  for datacenters.
  By characterizing modern server workloads and employing emerging memory subsystems,
  I look for minimizing the energy footprint and maximizing the compute density of
  server systems through specialization of various system components, and better system integration.

cv: files/cv.pdf
cv_updated: Feb. 2018

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

   # My name is Arash (Persian: آرش) (aka NEO), and I am from Iran. I am a PhD candidate at the School of Computer and Communication Sciences, EPFL, and a doctoral research assistant at PARSA under supervision of Prof. Babak Falsafi. I did my master’s in Software Engineering at the Department of CSE and IT of Shiraz University, where I also received my B.Sc. in Software Engineering.
